import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { dir } from "i18next";
import { i18nConfig } from "@/i18n-config";
import { getTranslation } from "@/utils/i18n";

import LangSwitcher from "@/components/LangSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  const { children } = props;

  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  }

  const headerData = getTranslation(locale, "layouts", "header.json");

  return (
    <html lang={locale} dir={dir(locale)}>
      <body>
        <LangSwitcher />
        {children}
      </body>
    </html>
  );
}
